hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/open/
  target: credit
  train: train.csv
  test: test.csv
  is_catboost: False
  cat_features:
  - income_total
  - income_type
  - edu_type
  - family_type
  - house_type
  - FLAG_MOBIL
  - work_phone
  - phone
  - occyp_type
  - begin_month
  - DAYS_BIRTH_month
  - DAYS_BIRTH_week
  - Age
  - DAYS_EMPLOYED_month
  - DAYS_EMPLOYED_week
  - before_EMPLOYED
  - before_EMPLOYED_month
  - before_EMPLOYED_week
  - user_code
experiment:
  project: ds-wook/cdal
  tags:
  - LightGBM
model:
  fold: 10
  params:
    reg_alpha: 5.998770177220496e-05
    reg_lambda: 0.07127674208132959
    max_depth: 18
    num_leaves: 125
    colsample_bytree: 0.4241631237880101
    subsample: 0.8876057928391585
    subsample_freq: 5
    min_child_samples: 5
    max_bin: 449
    boosting_type: gbdt
    learning_rate: 0.05
    n_estimators: 10000
    objective: multiclass
  path: models/10fold_lightgbm_models.pkl
  metric: multi_logloss
  early_stopping_rounds: 100
  search: False
  seed: 42
  verbose: 100
output:
  name: 10fold_lightgbm.csv
  path: output
