hydra:
  run:
    dir: ../log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/open/
  target: credit
  train: train.csv
  test: test.csv
  is_catboost: False
  cat_features:
  - income_total
  - income_type
  - edu_type
  - family_type
  - house_type
  - FLAG_MOBIL
  - work_phone
  - phone
  - occyp_type
  - begin_month
  - DAYS_BIRTH_month
  - DAYS_BIRTH_week
  - Age
  - DAYS_EMPLOYED_month
  - DAYS_EMPLOYED_week
  - before_EMPLOYED
  - before_EMPLOYED_month
  - before_EMPLOYED_week
  - user_code
  submit: sample_submission.csv
model:
  catboost: build/model/10fold_catboost_models.pkl
  lightgbm: build/model/10fold_lightgbm_models.pkl
  xgboost: build/model/10fold_xgboost_models.pkl
output:
  path: output
  name: build/output/10fold_lightgbm.csv