hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  path: input/open/
  target: credit
  train: train.csv
  test: test.csv
experiment:
  project: ds-wook/cdal
  tags:
  - XGBoost
model:
  fold: 5
  params:
    colsample_bytree: 0.44442679104045424
    gamma: 0.07361716094628554
    learning_rate: 0.0020428215357261676
    max_depth: 2
    min_child_weight: 5
    n_estimators: 10000
    n_jobs: -1
    objective: binary:logistic
    reg_alpha: 0.3916028672163949
    reg_lambda: 0.8398892426801621
    subsample: 0.8708229999183839
  path: models/5fold_xgboost_models.pkl
  metric: auc
  early_stopping_rounds: 100
  seed: 42
  verbose: 100
output:
  name: 5fold_xgboost.csv
  path: output
