hydra:
  run:
    dir: log/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: null
dataset:
  labels: train_labels.csv
  groups: sequence
  path: input/tabular-playground-series-apr-2022
  target: state
  train: train.csv
  test: test.csv
experiment:
  project: ds-wook/cdal
  tags:
    - XGBoost
    - Optuna
model:
  fold: 5
  params:
    n_estimators: 10000
    n_jobs: -1
    objective: binary:logistic
  path: models/5fold_xgboost_models.pkl
  metric: auc
  early_stopping_rounds: 100
  seed: 42
  verbose: 100
search:
  study_name: TPE Search
  direction: maximize
  seed: 42
  min_resource: 1
  max_resource: auto
  reduction_factor: 3
  n_trials: 100
  verbose: False
  path_name: config/modeling/xgb.yaml
  params_name: config/tuning/xgb.yaml
  colsample_bytree:
  - 0.4
  - 1.0
  gamma:
  - 0.01
  - 0.1
  learning_rate:
  - 0.001
  - 0.01
  max_depth:
  - 2
  - 10
  min_child_weight:
  - 3
  - 10
  reg_alpha:
  - 0.1
  - 0.5
  reg_lambda:
  - 0.3
  - 1.0
  subsample:
  - 0.3
  - 1.0